### ISSUE TITLE
Project analysis widget takes too much time to load

### ISSUE THREAD

**Issue by fserena** [SmartDeveloperHub/sdh-web#1]
![image](https://cloud.githubusercontent.com/assets/2788595/12941489/3680bbee-cfd3-11e5-8ae3-1d4cc1c78321.png)

**Comment by cblanco** [comment]
The problem is that too many metrics are required for this widget.

First, we need to "Director-costs". We need this value to calculate the relative costs of each product in the scatter plot.
Then, for each product (obtained from "view-director-products") this metrics:
1. product-cost
2. product-health
3. product-quality
4. product-timetomarket

eg 5 products -> 1 + 1 + 5 \* (4) = 22 requests.
